spring:
  datasource:
#    driverClassName: org.mariadb.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:log4jdbc:mariadb://198.13.47.188:19762/MINICOMMERCE?characterEncoding=UTF-8&serverTimezone=UTC
    username: mrbluesky
    password: kang12!@
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  mail:
    host: smtp.gmail.com
    port: 587
    username: 1234
    password: 1234
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8088

mybatis:
  mapper-locations:
    - mybatis/*.xml

logging:
  level:
    goods: debug